# Generated by Django 4.2.3 on 2023-07-19 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'meters',
            },
        ),
        migrations.CreateModel(
            name='MeterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField()),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meters.meter')),
            ],
            options={
                'db_table': 'meter_data',
            },
        ),
        migrations.AddIndex(
            model_name='meter',
            index=models.Index(fields=['name'], name='meters_name_ae1097_idx'),
        ),
        migrations.AddIndex(
            model_name='meterdata',
            index=models.Index(fields=['meter'], name='meter_data_meter_i_c0eb9d_idx'),
        ),
    ]
